### ISSUE TITLE
Typoes in Index

### ISSUE THREAD

**Issue by NatalieWolfe** [ryanwilliamquinn/tnf#1]
addtion -> addition: https://github.com/ryanwilliamquinn/tnf/blob/bac02a6fa6b9f58977a494ba63f4c938ff0a6c21/index.html#L59

i wrote -> I wrote: https://github.com/ryanwilliamquinn/tnf/blob/master/index.html#L65

time i was -> time I was; i worked -> I worked; though i was -> though I was: https://github.com/ryanwilliamquinn/tnf/blob/master/index.html#L80-L81

**Comment by ryanwilliamquinn** [comment]
Thanks @NatalieWolfe for the editing!

**Comment by NatalieWolfe** [comment]
My pleasure. :)
